# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cov_head <- function(x, n, offset) {
    .Call(`_fsummary_cov_head`, x, n, offset)
}

myrank <- function(v) {
    .Call(`_fsummary_myrank`, v)
}

center_split_df <- function(df, c_id, n_chain, n_iter) {
    .Call(`_fsummary_center_split_df`, df, c_id, n_chain, n_iter)
}

fftm <- function(x, k) {
    .Call(`_fsummary_fftm`, x, k)
}

fqnorm3v <- function(p) {
    .Call(`_fsummary_fqnorm3v`, p)
}

fqnorm <- function(p) {
    .Call(`_fsummary_fqnorm`, p)
}

fqnorm6v <- function(p) {
    .Call(`_fsummary_fqnorm6v`, p)
}

fqnorm7v <- function(p) {
    .Call(`_fsummary_fqnorm7v`, p)
}

