# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cov_head <- function(x, n, offset) {
    .Call(`_fsummary_cov_head`, x, n, offset)
}

myrank <- function(v) {
    .Call(`_fsummary_myrank`, v)
}

asort <- function(v) {
    .Call(`_fsummary_asort`, v)
}

myrank2 <- function(sv, o, res) {
    .Call(`_fsummary_myrank2`, sv, o, res)
}

myrank3 <- function(v, n) {
    .Call(`_fsummary_myrank3`, v, n)
}

center_split_df <- function(df, c_id, n_chain, n_iter) {
    .Call(`_fsummary_center_split_df`, df, c_id, n_chain, n_iter)
}

fftm <- function(x, k) {
    .Call(`_fsummary_fftm`, x, k)
}

fqnorm <- function(p) {
    .Call(`_fsummary_fqnorm`, p)
}

fzscale <- function(sx, o, res, n) {
    .Call(`_fsummary_fzscale`, sx, o, res, n)
}

