# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fftm <- function(x, k) {
    .Call(`_fsummary_fftm`, x, k)
}

cov_head <- function(x, n, offset) {
    .Call(`_fsummary_cov_head`, x, n, offset)
}

